-- Contas a receber (títulos em aberto) — base: Contas a Receber Postos.txt
SELECT
    CP.ID_FILIAL,
    ISNULL(CP.ID_ENTIDADE, 0) AS ID_ENTIDADE,
    ENT.NOMEENTIDADE,
    CP.HISTORICO,
    CP.NRODOC,
    CP.DTACONTA,
    CP.DTAVCTO,
    CASE WHEN CP.DTAVCTO < GETDATE() THEN 'VENCIDO' ELSE 'A VENCER' END AS SITUACAO,
    CP.VALOR,
    SUM(ISNULL(CPB.VALORBAIXA, 0)) AS VALORBAIXADO,
    CP.VALOR - SUM(ISNULL(CPB.VALORBAIXA, 0)) AS VALORFALTANTE,
    CASE
        WHEN (CP.VALOR - SUM(ISNULL(CPB.VALORBAIXA, 0))) = 0 THEN 'LIQUIDADO'
        ELSE 'PENDENTE'
    END AS STATUS
FROM CONTASRECEBER CP
LEFT JOIN CONTASRECEBERBAIXA CPB
    ON CP.ID_FILIAL = CPB.ID_FILIAL
    AND CP.ID_CONTASRECEBER = CPB.ID_CONTASRECEBER
LEFT JOIN ENTIDADES ENT
    ON CP.ID_FILIAL = ENT.ID_FILIAL
    AND CP.ID_ENTIDADE = ENT.ID_ENTIDADE
WHERE CP.DTAPGTO IS NULL
    AND CP.REFERENCIAPGTO IS NULL
    AND CP.DTACONTA <= GETDATE()
GROUP BY
    CP.ID_FILIAL,
    CP.ID_ENTIDADE,
    ENT.NOMEENTIDADE,
    CP.HISTORICO,
    CP.NRODOC,
    CP.ID_CONTASRECEBER,
    CP.DTACONTA,
    CP.DTAVCTO,
    CP.VALOR
ORDER BY CP.ID_FILIAL, CP.ID_ENTIDADE;
