-- Entradas de estoque (compras/outras entradas) — base: Entradas de Estoque.txt
-- SAIDAS_ENTRADAS IN (1, 9, 21). Confirmar domínio completo com o XPERT.
-- Pendente: chave NF-e, frete detalhado, vínculo com pedido.
SELECT DISTINCT
    MOVPRODUTOS.ID_FILIAL,
    NOMEFILIAL,
    MOVPRODUTOS.ID_DB,
    ITENSMOVPRODUTOS.ID_PRODUTOS,
    NOMEPRODUTO,
    NOMEENTIDADE,
    NROCOMPROVANTE,
    COMPROVANTES.VLRTOTAL AS TOTALCOMPROVANTE,
    COMPROVANTES.CFOP AS CFOPCOMPROVANTE,
    COMPROVANTES.DTACONTA,
    COMPROVANTES.DATA,
    COMPROVANTES.DTAEMISSAO,
    ITENSMOVPRODUTOS.QTDE,
    ITENSMOVPRODUTOS.VLRUNITARIO,
    ITENSMOVPRODUTOS.VLRCUSTOCOMICMS,
    CASE ITENSMOVPRODUTOS.VLRCUSTOSEMICMS
        WHEN 0 THEN ITENSMOVPRODUTOS.VLRUNITARIO
        ELSE ITENSMOVPRODUTOS.VLRCUSTOSEMICMS
    END AS VLRCUSTOSEMICMS,
    COMPROVANTES.REFERENCIA,
    COMPROVANTES.ID_COMPROVANTE,
    COMPROVANTES.ID_ENTIDADE,
    ITENSMOVPRODUTOS.CFOP AS CFOPPRODUTO,
    ITENSMOVPRODUTOS.ID_ITENSMOVPRODUTOS,
    CASE ITENSMOVPRODUTOS.VLRCUSTOSEMICMS
        WHEN 0 THEN ITENSMOVPRODUTOS.TOTAL
        ELSE (ITENSMOVPRODUTOS.QTDE * ITENSMOVPRODUTOS.VLRCUSTOSEMICMS)
    END AS TOTALITEM
FROM MOVPRODUTOS
INNER JOIN ITENSMOVPRODUTOS
    ON ITENSMOVPRODUTOS.ID_MOVPRODUTOS = MOVPRODUTOS.ID_MOVPRODUTOS
    AND ITENSMOVPRODUTOS.ID_DB = MOVPRODUTOS.ID_DB
    AND ITENSMOVPRODUTOS.ID_FILIAL = MOVPRODUTOS.ID_FILIAL
INNER JOIN PRODUTOS
    ON PRODUTOS.ID_PRODUTOS = ITENSMOVPRODUTOS.ID_PRODUTOS
    AND PRODUTOS.ID_FILIAL = ITENSMOVPRODUTOS.ID_FILIAL
INNER JOIN COMPROVANTES
    ON COMPROVANTES.ID_COMPROVANTE = MOVPRODUTOS.ID_COMPROVANTE
    AND COMPROVANTES.ID_DB = MOVPRODUTOS.ID_DB
    AND COMPROVANTES.ID_FILIAL = MOVPRODUTOS.ID_FILIAL
INNER JOIN ENTIDADES
    ON ENTIDADES.ID_ENTIDADE = COMPROVANTES.ID_ENTIDADE
    AND ENTIDADES.ID_FILIAL = COMPROVANTES.ID_FILIAL
INNER JOIN FILIAIS
    ON FILIAIS.ID_FILIAL = MOVPRODUTOS.ID_FILIAL
WHERE COMPROVANTES.SAIDAS_ENTRADAS IN (1, 9, 21)
    AND MOVPRODUTOS.ID_FILIAL IN (12290, 5301, 16709, 2443)
    AND COMPROVANTES.DTACONTA BETWEEN @P1 AND @P2
    AND COMPROVANTES.CANCELADO = 0
ORDER BY MOVPRODUTOS.ID_FILIAL, COMPROVANTES.NROCOMPROVANTE;
