-- Estoque atual por produto/local — base: Estoquea.txt
SELECT
    PRODUTOS.ID_FILIAL,
    PRODUTOS.ID_GRUPOPRODUTOS,
    GRUPOPRODUTOS.NOMEGRUPOPRODUTOS,
    PRODUTOSPORLOCALVENDA.ID_PRODUTOS,
    PRODUTOS.NOMEPRODUTO,
    PRODUTOS.UNIDADE,
    PRODUTOS.CUSTOMEDIO,
    PRODUTOS.CUSTOMEDIOCOMICMS,
    PRODUTOS.QTDETOTAL,
    PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS,
    LOCALVENDAS.NOMELOCALVENDAS,
    ESTOQUE.QTDEATUAL,
    PRODUTOSPORLOCALVENDA.VALOR1,
    PRODUTOSPORLOCALVENDA.VALOR2,
    PRODUTOSPORLOCALVENDA.VALOR3,
    PRODUTOSPORLOCALVENDA.VALOR4
FROM PRODUTOSPORLOCALVENDA
INNER JOIN PRODUTOS
    ON PRODUTOS.ID_PRODUTOS = PRODUTOSPORLOCALVENDA.ID_PRODUTOS
    AND ProdutosPorLocalVenda.ID_Filial = Produtos.ID_Filial
INNER JOIN LOCALVENDAS
    ON LOCALVENDAS.ID_LOCALVENDAS = PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS
    AND LocalVendas.ID_Filial = ProdutosPorLocalVenda.ID_Filial
INNER JOIN GRUPOPRODUTOS
    ON GRUPOPRODUTOS.ID_GRUPOPRODUTOS = PRODUTOS.ID_GRUPOPRODUTOS
    AND GrupoProdutos.ID_Filial = Produtos.ID_Filial
INNER JOIN ESTOQUE
    ON PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS = ESTOQUE.ID_LOCALVENDAS
    AND PRODUTOSPORLOCALVENDA.ID_PRODUTOS = ESTOQUE.ID_PRODUTOS
    AND ProdutosPorLocalVenda.ID_Filial = ESTOQUE.ID_Filial
    AND NOT PRODUTOS.ID_GRUPOPRODUTOS IN (
        SELECT ISNULL(GrupoServico, 0)
        FROM CfgGeral
        WHERE ID_FILIAL IN (12290, 5301, 16709, 2443)
    )
    AND PRODUTOS.ID_Filial IN (12290, 5301, 16709, 2443)
    AND PRODUTOS.Ativo = 1
ORDER BY Produtos.ID_Filial, PRODUTOS.ID_GRUPOPRODUTOS, PRODUTOS.NOMEPRODUTO;
