-- Faturamento / vendas (base: Faturamento Posto.txt)
-- Pendências: parametrizar datas e filial; validar CFOP (texto vs número);
-- incluir dia corrente se necessário para BI operacional.
SELECT
    FI.NomeFilial AS EMPRESA,
    CONVERT(DATE, (M.DATA)) AS DATA,
    M.ID_COMPROVANTE,
    COALESCE(E.ID_ENTIDADE, 0) AS ID_ENTIDADE,
    COALESCE(E.NOMEENTIDADE, 'CONSUMIDOR') AS NOMEENTIDADE,
    COALESCE(P.NOMEPRODUTO, 'SEM DESCRICAO') AS NOMEPRODUTO,
    CAST(ROUND(I.QTDE, 3) AS DECIMAL(15, 3)) AS QTDE,
    CAST(ROUND(I.PRECO_BASE_VENDA, 2) AS DECIMAL(15, 2)) AS PRECO_UN,
    CAST(ROUND(I.VLRDESCONTO, 2) AS DECIMAL(15, 2)) AS VLRDESCONTO,
    CAST(ROUND(I.TOTAL, 2) AS DECIMAL(15, 2)) AS TOTAL,
    CAST(ROUND(I.VLRCUSTO, 2) AS DECIMAL(15, 2)) AS VLRCUSTO,
    CAST(ROUND((I.QTDE * I.VLRCUSTO), 2) AS DECIMAL(15, 2)) AS CUSTOTOTAL,
    CAST(ROUND(I.TOTAL, 2) AS DECIMAL(15, 2))
        - CAST(ROUND((I.QTDE * I.VLRCUSTO), 2) AS DECIMAL(15, 2)) AS LUCROBRUTO,
    COALESCE(F.NOMEFUNCIONARIO, 'CAIXA') AS FRENTISTA,
    COALESCE(U.NOMEUSUARIOS, 'OPERADORA') AS OPERADORA,
    CASE M.FORMAPGTO
        WHEN 0 THEN 'Dinheiro'
        WHEN 1 THEN 'à Prazo'
        WHEN 2 THEN 'Chq Pre-Dta'
        WHEN 3 THEN 'Convênio C/C'
        WHEN 4 THEN 'Cartão Débito'
        WHEN 5 THEN 'Carta Frete'
        WHEN 6 THEN 'Dep. Bancário'
        WHEN 7 THEN 'Chq Vista'
        WHEN 8 THEN 'Moedas Div.'
        WHEN 9 THEN 'Outras'
        WHEN 16 THEN 'Cartão Fidelidade'
        ELSE 'Outros'
    END AS FORMA
FROM ITENSMOVPRODUTOS I
LEFT JOIN MOVPRODUTOS M
    ON I.ID_MOVPRODUTOS = M.ID_MOVPRODUTOS
    AND I.ID_FILIAL = M.ID_FILIAL
    AND I.ID_DB = M.ID_DB
LEFT JOIN PRODUTOS P
    ON P.ID_PRODUTOS = I.ID_PRODUTOS
    AND P.ID_FILIAL = I.ID_FILIAL
LEFT JOIN FUNCIONARIOS F
    ON F.ID_FUNCIONARIOS = I.ID_FUNCIONARIOS
    AND F.ID_FILIAL = I.ID_FILIAL
LEFT JOIN ENTIDADES E
    ON E.ID_ENTIDADE = M.ID_ENTIDADE
    AND E.ID_FILIAL = M.ID_FILIAL
LEFT JOIN COMPROVANTES C
    ON C.ID_COMPROVANTE = M.ID_COMPROVANTE
    AND C.ID_FILIAL = M.ID_FILIAL
    AND C.ID_DB = M.ID_DB
LEFT JOIN USUARIOS U
    ON U.ID_USUARIOS = C.ID_USUARIOS
    AND U.ID_FILIAL = C.ID_FILIAL
LEFT JOIN FILIAIS FI
    ON FI.ID_FILIAL = M.ID_FILIAL
WHERE CONVERT(DATE, (M.DATA)) BETWEEN CONVERT(DATE, ('2023-01-01')) AND GETDATE() - 1
    AND C.CANCELADO = 0
    AND I.CFOP > '3000';
