-- Posição atual de produtos — base: Posição Atual de Produtos.txt
SELECT
    Produtos.ID_FILIAL,
    PRODUTOS.ID_PRODUTOS,
    PRODUTOS.NOMEPRODUTO,
    PRODUTOS.UNIDADE,
    PRODUTOS.CUSTOMEDIO,
    PRODUTOS.ID_GRUPOPRODUTOS,
    GRUPOPRODUTOS.NOMEGRUPOPRODUTOS,
    PRODUTOS.QTDETOTAL,
    PRODUTOSPORLOCALVENDA.VALOR1
FROM PRODUTOSPORLOCALVENDA
INNER JOIN PRODUTOS
    ON PRODUTOSPORLOCALVENDA.ID_PRODUTOS = PRODUTOS.ID_PRODUTOS
    AND PRODUTOSPORLOCALVENDA.ID_FILIAL = PRODUTOS.ID_FILIAL
INNER JOIN GRUPOPRODUTOS
    ON GRUPOPRODUTOS.ID_GRUPOPRODUTOS = PRODUTOS.ID_GRUPOPRODUTOS
    AND GRUPOPRODUTOS.ID_FILIAL = PRODUTOS.ID_FILIAL
WHERE PRODUTOS.ID_FILIAL IN (12290, 5301, 16709, 2443)
    AND PRODUTOS.ID_LOCALVENDAS = PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS
    AND PRODUTOS.ATIVO = 1
ORDER BY PRODUTOS.ID_FILIAL, PRODUTOS.ID_GRUPOPRODUTOS, PRODUTOS.ID_PRODUTOS;
