-- Preço praticado nas vendas por dia — base: Preço de Produtos por Dia.txt
-- SAIDAS_ENTRADAS = 0 (saídas). STATUS <> 2 (excluir cancelados/ajustes — confirmar).
SELECT
    ITENSMOVPRODUTOS.ID_FILIAL,
    FILIAIS.NOMEFILIAL,
    ITENSMOVPRODUTOS.ID_PRODUTOS,
    PRODUTOS.NOMEPRODUTO,
    MOVPRODUTOS.DTACONTA,
    ITENSMOVPRODUTOS.VLRUNITARIO,
    MIN(MOVPRODUTOS.DATA) AS INICIOPERIODO,
    MAX(MOVPRODUTOS.DATA) AS FINALPERIODO
FROM ITENSMOVPRODUTOS
INNER JOIN MOVPRODUTOS
    ON ITENSMOVPRODUTOS.ID_MOVPRODUTOS = MOVPRODUTOS.ID_MOVPRODUTOS
    AND ITENSMOVPRODUTOS.ID_FILIAL = MOVPRODUTOS.ID_FILIAL
INNER JOIN PRODUTOS
    ON ITENSMOVPRODUTOS.ID_PRODUTOS = PRODUTOS.ID_PRODUTOS
    AND ITENSMOVPRODUTOS.ID_FILIAL = PRODUTOS.ID_FILIAL
INNER JOIN FILIAIS
    ON ITENSMOVPRODUTOS.ID_FILIAL = FILIAIS.ID_FILIAL
WHERE CONVERT(VARCHAR(10), MOVPRODUTOS.DTACONTA, 120) BETWEEN '2026-07-01' AND '2026-07-08'
    AND SAIDAS_ENTRADAS = 0
    AND ITENSMOVPRODUTOS.STATUS <> 2
    AND ITENSMOVPRODUTOS.ID_FILIAL IN (12290, 5301, 16709, 2443)
GROUP BY
    ITENSMOVPRODUTOS.ID_FILIAL,
    FILIAIS.NOMEFILIAL,
    ITENSMOVPRODUTOS.ID_PRODUTOS,
    PRODUTOS.NOMEPRODUTO,
    MOVPRODUTOS.DTACONTA,
    ITENSMOVPRODUTOS.VLRUNITARIO
ORDER BY
    ITENSMOVPRODUTOS.ID_FILIAL,
    MOVPRODUTOS.DTACONTA,
    MIN(MOVPRODUTOS.DATA),
    MAX(MOVPRODUTOS.DATA);
