-- Preço de venda por local — base: Preço de venda.txt
SELECT
    PRODUTOSPORLOCALVENDA.ID_FILIAL,
    NOMEFILIAL,
    produtos.ID_PRODUTOS,
    GRUPOPRODUTOS.ID_GRUPOPRODUTOS,
    PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS,
    PRODUTOS.NOMEPRODUTO,
    NOMEGRUPOPRODUTOS,
    ESTOQUE.QTDEATUAL,
    PRODUTOS.ULTVLRENTRADA,
    NOMELOCALVENDAS,
    PRODUTOSPORLOCALVENDA.VALOR1,
    PRODUTOSPORLOCALVENDA.VALOR2,
    PRODUTOSPORLOCALVENDA.VALOR3,
    PRODUTOSPORLOCALVENDA.VALOR4,
    PRODUTOS.CUSTOMEDIO,
    QTDEATUAL * VALOR1 AS TOTAL_VALOR1,
    QTDEATUAL * CUSTOMEDIO AS TOTAL_CUSTOMEDIO,
    QTDEATUAL * ULTVLRENTRADA AS TOTAL_VLRCOMPRA
FROM PRODUTOSPORLOCALVENDA
INNER JOIN ESTOQUE
    ON ESTOQUE.ID_LOCALVENDAS = PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS
    AND ESTOQUE.ID_FILIAL = PRODUTOSPORLOCALVENDA.ID_FILIAL
INNER JOIN PRODUTOS
    ON PRODUTOS.ID_PRODUTOS = PRODUTOSPORLOCALVENDA.ID_PRODUTOS
    AND ESTOQUE.ID_PRODUTOS = PRODUTOS.ID_PRODUTOS
    AND PRODUTOS.ID_FILIAL = PRODUTOSPORLOCALVENDA.ID_FILIAL
INNER JOIN GRUPOPRODUTOS
    ON GRUPOPRODUTOS.ID_GRUPOPRODUTOS = PRODUTOS.ID_GRUPOPRODUTOS
    AND GRUPOPRODUTOS.ID_FILIAL = PRODUTOS.ID_FILIAL
INNER JOIN LOCALVENDAS
    ON LOCALVENDAS.ID_LOCALVENDAS = PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS
    AND LOCALVENDAS.ID_FILIAL = PRODUTOSPORLOCALVENDA.ID_FILIAL
INNER JOIN FILIAIS
    ON FILIAIS.ID_FILIAL = PRODUTOSPORLOCALVENDA.ID_FILIAL
WHERE PRODUTOSPORLOCALVENDA.ID_FILIAL IN (12290, 5301, 16709, 2443)
    AND PRODUTOS.ATIVO = 1
    AND PRODUTOSPORLOCALVENDA.ATIVO = 1
ORDER BY
    PRODUTOSPORLOCALVENDA.ID_FILIAL,
    PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS,
    GRUPOPRODUTOS.ID_GRUPOPRODUTOS,
    produtos.ID_PRODUTOS;
