-- Cadastro de produtos — base: Produtos.txt
-- Parametrizar @ID_FILIAL no conector.
SELECT
    PRODUTOS.ID_PRODUTOS,
    PRODUTOS.NOMEPRODUTO AS DESCRICAO,
    PRODUTOSSIMILARES.PRODUTOSIMILAR,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    PRODUTOS.QTDETOTAL AS QUANTIDADE
FROM PRODUTOS
LEFT JOIN PRODUTOSSIMILARES
    ON PRODUTOS.ID_FILIAL = PRODUTOSSIMILARES.ID_FILIAL
    AND PRODUTOS.ID_PRODUTOS = PRODUTOSSIMILARES.ID_PRODUTOS
LEFT JOIN PRODUTOSPORLOCALVENDA
    ON PRODUTOS.ID_FILIAL = PRODUTOSPORLOCALVENDA.ID_FILIAL
    AND PRODUTOS.ID_LOCALVENDAS = PRODUTOSPORLOCALVENDA.ID_LOCALVENDAS
    AND PRODUTOSPORLOCALVENDA.ID_PRODUTOS = PRODUTOS.ID_PRODUTOS
WHERE PRODUTOS.ID_FILIAL = @ID_FILIAL
    AND PRODUTOS.ATIVO = 1
ORDER BY PRODUTOS.ID_PRODUTOS;
