from decimal import Decimal

from app.core.quote_comparison_enums import METHODOLOGY_VERSION

ROUNDING = "ROUND_HALF_UP"
LITER_DISPLAY_SCALE = Decimal("0.0001")
LITER_PERSIST_SCALE = Decimal("0.00000001")
TOTAL_DISPLAY_SCALE = Decimal("0.01")
TOTAL_PERSIST_SCALE = Decimal("0.0001")
RATE_PERSIST_SCALE = Decimal("0.000000000001")

METHODOLOGY_VERSION_DEFAULT = METHODOLOGY_VERSION
