"""Enums Sprint 9 — índices externos."""

from enum import StrEnum


class ExternalSourceType(StrEnum):
    API = "API"
    CSV = "CSV"
    XLSX = "XLSX"
    MANUAL = "MANUAL"
    AUTHORIZED_WEB = "AUTHORIZED_WEB"


class ExternalSourceStatus(StrEnum):
    MISCONFIGURED = "MISCONFIGURED"
    READY_FOR_MANUAL = "READY_FOR_MANUAL"
    HOMOLOGATED = "HOMOLOGATED"
    SCHEDULED = "SCHEDULED"
    SUSPENDED = "SUSPENDED"


class ExternalSeriesFrequency(StrEnum):
    INTRADAY = "INTRADAY"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    IRREGULAR = "IRREGULAR"


class ExternalCalendarType(StrEnum):
    CALENDAR_DAYS = "CALENDAR_DAYS"
    BUSINESS_DAYS = "BUSINESS_DAYS"
    SOURCE_SPECIFIC = "SOURCE_SPECIFIC"


class ExternalUnit(StrEnum):
    USD_PER_BARREL = "USD_PER_BARREL"
    BRL_PER_USD = "BRL_PER_USD"
    BRL_PER_LITER = "BRL_PER_LITER"
    BRL_PER_CUBIC_METER = "BRL_PER_CUBIC_METER"
    PERCENT = "PERCENT"
    INDEX_POINTS = "INDEX_POINTS"


class ObservationRevisionStatus(StrEnum):
    CURRENT = "CURRENT"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class IngestionTriggerType(StrEnum):
    MANUAL = "MANUAL"
    SCHEDULER = "SCHEDULER"
    IMPORT = "IMPORT"
    RETRY = "RETRY"
    BACKFILL = "BACKFILL"


class IngestionRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class ImportParseStatus(StrEnum):
    PENDING = "PENDING"
    PREVIEWED = "PREVIEWED"
    APPLIED = "APPLIED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class FreshnessStatus(StrEnum):
    FRESH = "FRESH"
    DUE_SOON = "DUE_SOON"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"


class QualityIssueCode(StrEnum):
    MISSING_VALUE = "MISSING_VALUE"
    INVALID_DATE = "INVALID_DATE"
    INVALID_UNIT = "INVALID_UNIT"
    INVALID_CURRENCY = "INVALID_CURRENCY"
    DUPLICATE_OBSERVATION = "DUPLICATE_OBSERVATION"
    CONFLICTING_OBSERVATION = "CONFLICTING_OBSERVATION"
    OUT_OF_ORDER_OBSERVATION = "OUT_OF_ORDER_OBSERVATION"
    UNEXPECTED_FREQUENCY = "UNEXPECTED_FREQUENCY"
    SOURCE_DELAYED = "SOURCE_DELAYED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    VALUE_OUTLIER = "VALUE_OUTLIER"
    REVISION_DETECTED = "REVISION_DETECTED"
    PARSER_ERROR = "PARSER_ERROR"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"


class QualitySeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class QualityResolutionStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class ObservationApplyResult(StrEnum):
    INSERTED = "INSERTED"
    SKIPPED_UNCHANGED = "SKIPPED_UNCHANGED"
    NEW_REVISION = "NEW_REVISION"
    REJECTED = "REJECTED"
