from enum import StrEnum


class PaymentMethodGroup(StrEnum):
    CASH = "CASH"
    PIX = "PIX"
    DEBIT_CARD = "DEBIT_CARD"
    CREDIT_CARD = "CREDIT_CARD"
    FLEET = "FLEET"
    INVOICE = "INVOICE"
    VOUCHER = "VOUCHER"
    OTHER = "OTHER"
    UNMAPPED = "UNMAPPED"


class FuelOperationType(StrEnum):
    SALE = "SALE"
    RETURN = "RETURN"
    ADJUSTMENT = "ADJUSTMENT"


class MarginStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    PARTIAL = "PARTIAL"


class MetricEligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    ELIGIBLE_WITH_WARNINGS = "ELIGIBLE_WITH_WARNINGS"
    EXCLUDED = "EXCLUDED"


class MetricExclusionReason(StrEnum):
    UNMAPPED_PRODUCT = "UNMAPPED_PRODUCT"
    IGNORED_PRODUCT = "IGNORED_PRODUCT"
    INVALID_VOLUME = "INVALID_VOLUME"
    UNIT_CONVERSION_REQUIRED = "UNIT_CONVERSION_REQUIRED"
    MISSING_NET_AMOUNT = "MISSING_NET_AMOUNT"
    MISSING_COST = "MISSING_COST"
    COST_COMPONENT_MISMATCH = "COST_COMPONENT_MISMATCH"
    CANCELLED_SALE = "CANCELLED_SALE"
    MIXED_OR_UNALLOCATED_PAYMENT = "MIXED_OR_UNALLOCATED_PAYMENT"
    NEGATIVE_GROSS_MARGIN = "NEGATIVE_GROSS_MARGIN"
    INVALID_BUSINESS_DATE = "INVALID_BUSINESS_DATE"
    CROSS_ORGANIZATION_REFERENCE = "CROSS_ORGANIZATION_REFERENCE"


class CostSource(StrEnum):
    ERP_RECORDED_COST = "ERP_RECORDED_COST"


class PriceHistorySource(StrEnum):
    SOURCE_EFFECTIVE_DATE = "SOURCE_EFFECTIVE_DATE"
    OBSERVED_BY_SYNC = "OBSERVED_BY_SYNC"


class FuelSalesFreshnessStatus(StrEnum):
    UPDATED = "UPDATED"
    DELAYED = "DELAYED"
    STALE = "STALE"
    UNAVAILABLE = "UNAVAILABLE"
    UNSAFE_SOURCE = "UNSAFE_SOURCE"


class ReconciliationRunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
