from enum import StrEnum


class PurchaseOperationType(StrEnum):
    PURCHASE = "PURCHASE"
    PURCHASE_RETURN = "PURCHASE_RETURN"
    ADJUSTMENT = "ADJUSTMENT"
    UNKNOWN = "UNKNOWN"


class PurchaseMetricEligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    ELIGIBLE_WITH_WARNINGS = "ELIGIBLE_WITH_WARNINGS"
    EXCLUDED = "EXCLUDED"


class PurchaseMetricExclusionReason(StrEnum):
    UNMAPPED_PRODUCT = "UNMAPPED_PRODUCT"
    IGNORED_PRODUCT = "IGNORED_PRODUCT"
    MISSING_ERP_PRODUCT_REFERENCE = "MISSING_ERP_PRODUCT_REFERENCE"
    UNMAPPED_SUPPLIER = "UNMAPPED_SUPPLIER"
    IGNORED_SUPPLIER = "IGNORED_SUPPLIER"
    MISSING_ERP_SUPPLIER_REFERENCE = "MISSING_ERP_SUPPLIER_REFERENCE"
    INVALID_ACCESS_KEY = "INVALID_ACCESS_KEY"
    DUPLICATE_ACCESS_KEY = "DUPLICATE_ACCESS_KEY"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    UNIT_CONVERSION_REQUIRED = "UNIT_CONVERSION_REQUIRED"
    MISSING_ITEM_COST = "MISSING_ITEM_COST"
    COST_COMPONENT_MISMATCH = "COST_COMPONENT_MISMATCH"
    INVOICE_TOTAL_MISMATCH = "INVOICE_TOTAL_MISMATCH"
    CANCELLED_INVOICE = "CANCELLED_INVOICE"
    PURCHASE_RETURN = "PURCHASE_RETURN"
    EXCLUDED_NON_FUEL_PRODUCT = "EXCLUDED_NON_FUEL_PRODUCT"
    CROSS_STATION_DATA_LEAK = "CROSS_STATION_DATA_LEAK"
    COST_PER_LITER_UNAVAILABLE = "COST_PER_LITER_UNAVAILABLE"


class PurchaseCostConcept(StrEnum):
    ERP_RECORDED_COST = "ERP_RECORDED_COST"
    COMMERCIAL_DELIVERED_COST = "COMMERCIAL_DELIVERED_COST"
    ACCOUNTING_COST = "ACCOUNTING_COST"


class AllocationMethod(StrEnum):
    PROPORTIONAL_GROSS_AMOUNT = "PROPORTIONAL_GROSS_AMOUNT"
    ITEM_PROVIDED = "ITEM_PROVIDED"
    NONE = "NONE"


class GrossAmountSource(StrEnum):
    SOURCE_ITEM_TOTAL = "SOURCE_ITEM_TOTAL"
    QUANTITY_TIMES_UNIT_PRICE = "QUANTITY_TIMES_UNIT_PRICE"


class NfeParseStatus(StrEnum):
    PENDING = "PENDING"
    PARSED = "PARSED"
    PARSE_ERROR = "PARSE_ERROR"
    SKIPPED = "SKIPPED"


class NfeReconciliationStatus(StrEnum):
    MATCHED = "MATCHED"
    MATCHED_WITH_WARNINGS = "MATCHED_WITH_WARNINGS"
    MISMATCH = "MISMATCH"
    XML_MISSING = "XML_MISSING"
    ERP_DOCUMENT_MISSING = "ERP_DOCUMENT_MISSING"
    PARSE_ERROR = "PARSE_ERROR"
    PENDING = "PENDING"


class AccountsPayableNormalizedStatus(StrEnum):
    OPEN = "OPEN"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"
    RENEGOTIATED = "RENEGOTIATED"
    UNKNOWN = "UNKNOWN"


class AgingBucket(StrEnum):
    OVERDUE = "OVERDUE"
    D0_7 = "0_7"
    D8_15 = "8_15"
    D16_30 = "16_30"
    D31_60 = "31_60"
    OVER_60 = "OVER_60"


class WeightedTermBase(StrEnum):
    ENTRY_DATE = "ENTRY_DATE"
    ISSUE_DATE = "ISSUE_DATE"


class InvoiceLinkStatus(StrEnum):
    LINKED = "LINKED"
    PENDING_INVOICE_LINK = "PENDING_INVOICE_LINK"
    UNLINKED = "UNLINKED"


class FuelPurchasesFreshnessStatus(StrEnum):
    UPDATED = "UPDATED"
    DELAYED = "DELAYED"
    STALE = "STALE"
    UNAVAILABLE = "UNAVAILABLE"
    UNSAFE_SOURCE = "UNSAFE_SOURCE"
