"""Enums Sprint 10 — correlação, defasagem e repasse."""

from enum import StrEnum


class MarketAnalysisType(StrEnum):
    CORRELATION = "CORRELATION"
    LAG_ANALYSIS = "LAG_ANALYSIS"
    PASS_THROUGH = "PASS_THROUGH"
    ASYMMETRY = "ASYMMETRY"
    FULL = "FULL"


class MarketAnalysisStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"


class MarketTransformation(StrEnum):
    LEVEL = "LEVEL"
    ABSOLUTE_CHANGE = "ABSOLUTE_CHANGE"
    PERCENTAGE_CHANGE = "PERCENTAGE_CHANGE"
    BASE_100 = "BASE_100"


class MarketFrequency(StrEnum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    IRREGULAR = "IRREGULAR"


class AlignmentPolicy(StrEnum):
    EXACT_DATE = "EXACT_DATE"
    AGGREGATE_INTERNAL_TO_WEEKLY = "AGGREGATE_INTERNAL_TO_WEEKLY"
    CARRY_FORWARD_EXTERNAL = "CARRY_FORWARD_EXTERNAL"


class CorrelationMethod(StrEnum):
    PEARSON = "PEARSON"
    SPEARMAN = "SPEARMAN"


class InternalSeriesType(StrEnum):
    QUOTE_BEST_DELIVERED_COST = "QUOTE_BEST_DELIVERED_COST"
    QUOTE_AVERAGE_DELIVERED_COST = "QUOTE_AVERAGE_DELIVERED_COST"
    QUOTE_DISTRIBUTOR_DELIVERED_COST = "QUOTE_DISTRIBUTOR_DELIVERED_COST"
    QUOTE_FINANCIAL_EQUIVALENT_COST = "QUOTE_FINANCIAL_EQUIVALENT_COST"
    PURCHASE_ACTUAL_DELIVERED_COST = "PURCHASE_ACTUAL_DELIVERED_COST"
    PURCHASE_VOLUME_WEIGHTED_COST = "PURCHASE_VOLUME_WEIGHTED_COST"
    PURCHASE_DISTRIBUTOR_COST = "PURCHASE_DISTRIBUTOR_COST"
    RETAIL_POSTED_PRICE = "RETAIL_POSTED_PRICE"
    RETAIL_WEIGHTED_AVERAGE_PRICE = "RETAIL_WEIGHTED_AVERAGE_PRICE"
    RETAIL_NET_REALIZED_PRICE = "RETAIL_NET_REALIZED_PRICE"
    RETAIL_GROSS_MARGIN_PER_LITER = "RETAIL_GROSS_MARGIN_PER_LITER"
    # séries sintéticas / proxy
    SYNTHETIC_INTERNAL = "SYNTHETIC_INTERNAL"
    BRENT_BRL_PER_BARREL_PROXY = "BRENT_BRL_PER_BARREL_PROXY"
    BRENT_BRL_PER_LITER_PROXY = "BRENT_BRL_PER_LITER_PROXY"


class MetricType(StrEnum):
    PEARSON = "PEARSON"
    SPEARMAN = "SPEARMAN"
    CROSS_CORRELATION_LAG = "CROSS_CORRELATION_LAG"
    SELECTED_LAG = "SELECTED_LAG"
    PASS_THROUGH_RATIO = "PASS_THROUGH_RATIO"
    PASS_THROUGH_ELASTICITY = "PASS_THROUGH_ELASTICITY"
    UPWARD_PASS_THROUGH = "UPWARD_PASS_THROUGH"
    DOWNWARD_PASS_THROUGH = "DOWNWARD_PASS_THROUGH"
    ASYMMETRY = "ASYMMETRY"


class QualityStatus(StrEnum):
    VALID = "VALID"
    VALID_WITH_WARNINGS = "VALID_WITH_WARNINGS"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"
    LOW_COVERAGE = "LOW_COVERAGE"
    STALE_SOURCE = "STALE_SOURCE"
    EXCESSIVE_MISSING_VALUES = "EXCESSIVE_MISSING_VALUES"
    CONSTANT_SERIES = "CONSTANT_SERIES"
    OUTLIER_SENSITIVE = "OUTLIER_SENSITIVE"
    NO_VARIATION = "NO_VARIATION"
    NOT_COMPARABLE = "NOT_COMPARABLE"
    PASS_THROUGH_UNAVAILABLE = "PASS_THROUGH_UNAVAILABLE"
    FAILED = "FAILED"


class EventDirection(StrEnum):
    UPWARD = "UPWARD"
    DOWNWARD = "DOWNWARD"
    FLAT = "FLAT"


class LagUnit(StrEnum):
    DAYS = "DAYS"
    PERIODS = "PERIODS"


class AnalysisTriggerType(StrEnum):
    MANUAL = "MANUAL"
    REPROCESS = "REPROCESS"
    SYNTHETIC = "SYNTHETIC"
    SCHEDULED = "SCHEDULED"
