"""Enums Sprint 12 — alertas, saúde, SLO e prontidão."""

from enum import StrEnum


class AlertType(StrEnum):
    BUSINESS = "BUSINESS"
    DATA_QUALITY = "DATA_QUALITY"
    INTEGRATION = "INTEGRATION"
    SECURITY = "SECURITY"
    WORKFLOW = "WORKFLOW"
    FINANCIAL = "FINANCIAL"
    MARKET = "MARKET"
    SYSTEM = "SYSTEM"


class AlertSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertPriority(StrEnum):
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"


class AlertStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"
    SNOOZED = "SNOOZED"
    EXPIRED = "EXPIRED"


class AlertOperator(StrEnum):
    GT = "GT"
    GTE = "GTE"
    LT = "LT"
    LTE = "LTE"
    EQ = "EQ"
    NE = "NE"
    PERCENT_CHANGE_GT = "PERCENT_CHANGE_GT"
    PERCENT_CHANGE_LT = "PERCENT_CHANGE_LT"
    MISSING = "MISSING"
    STALE = "STALE"
    STATUS_IN = "STATUS_IN"


class ResolutionCode(StrEnum):
    FIXED = "FIXED"
    DATA_CORRECTED = "DATA_CORRECTED"
    MAPPING_COMPLETED = "MAPPING_COMPLETED"
    CONFIGURATION_CHANGED = "CONFIGURATION_CHANGED"
    EXPECTED_BEHAVIOR = "EXPECTED_BEHAVIOR"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    ACCEPTED_RISK = "ACCEPTED_RISK"
    DUPLICATE = "DUPLICATE"
    OTHER = "OTHER"


class MetricQualityStatus(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NO_DATA = "NO_DATA"
    NOT_SYNCED = "NOT_SYNCED"
    STALE = "STALE"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    ERROR = "ERROR"


class FreshnessStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"
    NOT_SYNCED = "NOT_SYNCED"


class ComponentHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"
    UNKNOWN = "UNKNOWN"
    UNSAFE = "UNSAFE"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    DEAD_LETTER = "DEAD_LETTER"


class IncidentSeverity(StrEnum):
    SEV1 = "SEV1"
    SEV2 = "SEV2"
    SEV3 = "SEV3"
    SEV4 = "SEV4"


class IncidentStatus(StrEnum):
    DETECTED = "DETECTED"
    INVESTIGATING = "INVESTIGATING"
    MITIGATING = "MITIGATING"
    MONITORING = "MONITORING"
    RESOLVED = "RESOLVED"
    POSTMORTEM_REQUIRED = "POSTMORTEM_REQUIRED"


class ReadinessStatus(StrEnum):
    READY = "READY"
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    NOT_READY = "NOT_READY"


class NotificationChannel(StrEnum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"


class NotificationStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


# Alert codes obrigatórios (subset fundação)
class AlertCode(StrEnum):
    UNSAFE_XPERT_SOURCE = "UNSAFE_XPERT_SOURCE"
    PRODUCTION_UNSAFE_SOURCE_ATTEMPT = "PRODUCTION_UNSAFE_SOURCE_ATTEMPT"
    SYNC_FAILED = "SYNC_FAILED"
    SYNC_PARTIAL = "SYNC_PARTIAL"
    SYNC_STUCK = "SYNC_STUCK"
    SYNC_HEARTBEAT_LOST = "SYNC_HEARTBEAT_LOST"
    CHECKPOINT_NOT_ADVANCING = "CHECKPOINT_NOT_ADVANCING"
    CONTRACT_INVALID = "CONTRACT_INVALID"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    STALE_DATASET = "STALE_DATASET"
    COVERAGE_DROP = "COVERAGE_DROP"
    CROSS_STATION_DATA_LEAK = "CROSS_STATION_DATA_LEAK"
    DUPLICATE_FACT = "DUPLICATE_FACT"
    MISSING_MAPPING = "MISSING_MAPPING"
    MISSING_COST = "MISSING_COST"
    MISSING_VOLUME = "MISSING_VOLUME"
    NEGATIVE_GROSS_MARGIN = "NEGATIVE_GROSS_MARGIN"
    MARGIN_BELOW_FLOOR = "MARGIN_BELOW_FLOOR"
    PRICING_APPROVAL_OVERDUE = "PRICING_APPROVAL_OVERDUE"
    APPROVED_PRICE_NOT_IMPLEMENTED = "APPROVED_PRICE_NOT_IMPLEMENTED"
    IMPLEMENTED_PRICE_DIFFERENT = "IMPLEMENTED_PRICE_DIFFERENT"
    COMPARISON_COVERAGE_MISMATCH = "COMPARISON_COVERAGE_MISMATCH"
    SCHEDULER_BLOCKED = "SCHEDULER_BLOCKED"
    QUOTE_AI_PROCESSING_FAILED = "QUOTE_AI_PROCESSING_FAILED"
    QUOTE_AI_PROVIDER_UNAVAILABLE = "QUOTE_AI_PROVIDER_UNAVAILABLE"
    QUOTE_AI_BUDGET_EXCEEDED = "QUOTE_AI_BUDGET_EXCEEDED"
    QUOTE_AI_LOW_CONFIDENCE = "QUOTE_AI_LOW_CONFIDENCE"
    QUOTE_AI_REVIEW_OVERDUE = "QUOTE_AI_REVIEW_OVERDUE"
    QUOTE_AI_DUPLICATE_DOCUMENT = "QUOTE_AI_DUPLICATE_DOCUMENT"
    QUOTE_AI_PROMPT_INJECTION_DETECTED = "QUOTE_AI_PROMPT_INJECTION_DETECTED"
    QUOTE_AI_HIGH_CORRECTION_RATE = "QUOTE_AI_HIGH_CORRECTION_RATE"
    QUOTE_AI_COST_SPIKE = "QUOTE_AI_COST_SPIKE"
