"""Enums Sprint 11 — formação de preço, margem e aprovação."""

from enum import StrEnum


class PriceType(StrEnum):
    POSTED_PRICE = "POSTED_PRICE"
    CASH_PRICE = "CASH_PRICE"
    DEBIT_PRICE = "DEBIT_PRICE"
    CREDIT_PRICE = "CREDIT_PRICE"
    CONVENIO_PRICE = "CONVENIO_PRICE"


class CostBasisType(StrEnum):
    LAST_CONFIRMED_PURCHASE = "LAST_CONFIRMED_PURCHASE"
    WEIGHTED_PURCHASE_COST = "WEIGHTED_PURCHASE_COST"
    BEST_CURRENT_ELIGIBLE_QUOTE = "BEST_CURRENT_ELIGIBLE_QUOTE"
    AVERAGE_ELIGIBLE_QUOTE = "AVERAGE_ELIGIBLE_QUOTE"
    CONSERVATIVE_MAX = "CONSERVATIVE_MAX"
    MANUAL_APPROVED_COST = "MANUAL_APPROVED_COST"
    SYNTHETIC_COST = "SYNTHETIC_COST"


class CostConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNAVAILABLE = "UNAVAILABLE"


class RoundingPolicy(StrEnum):
    NONE = "NONE"
    NEAREST_CENT = "NEAREST_CENT"
    END_WITH_9 = "END_WITH_9"
    END_WITH_99 = "END_WITH_99"
    CUSTOM_INCREMENT = "CUSTOM_INCREMENT"


class PricingScenarioType(StrEnum):
    CONSERVATIVE = "CONSERVATIVE"
    BALANCED = "BALANCED"
    COMPETITIVE = "COMPETITIVE"


class RecommendationStatus(StrEnum):
    HOLD = "HOLD"
    INCREASE = "INCREASE"
    DECREASE = "DECREASE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NO_RECOMMENDATION = "NO_RECOMMENDATION"


class PricingQualityStatus(StrEnum):
    READY = "READY"
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    MISSING_COST = "MISSING_COST"
    MISSING_PRICE = "MISSING_PRICE"
    STALE_COST = "STALE_COST"
    STALE_PRICE = "STALE_PRICE"
    LOW_COST_CONFIDENCE = "LOW_COST_CONFIDENCE"
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    MISSING_VOLUME_REFERENCE = "MISSING_VOLUME_REFERENCE"
    MARKET_SIGNAL_UNAVAILABLE = "MARKET_SIGNAL_UNAVAILABLE"
    UNMAPPED_PRODUCT = "UNMAPPED_PRODUCT"
    SOURCE_NOT_RELIABLE = "SOURCE_NOT_RELIABLE"
    NOT_COMPARABLE = "NOT_COMPARABLE"


class PricingRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DecisionStatus(StrEnum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    APPROVED_PENDING_IMPLEMENTATION = "APPROVED_PENDING_IMPLEMENTATION"
    IMPLEMENTED_MATCHED = "IMPLEMENTED_MATCHED"
    IMPLEMENTED_DIFFERENT = "IMPLEMENTED_DIFFERENT"
    IMPLEMENTATION_NOT_CONFIRMED = "IMPLEMENTATION_NOT_CONFIRMED"


class ApprovalDecision(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ImplementationCheckStatus(StrEnum):
    MATCHED = "MATCHED"
    WITHIN_TOLERANCE = "WITHIN_TOLERANCE"
    DIFFERENT = "DIFFERENT"
    NOT_FOUND = "NOT_FOUND"
    STALE_PRICE_SNAPSHOT = "STALE_PRICE_SNAPSHOT"
    MANUAL_CONFIRMED = "MANUAL_CONFIRMED"


class RecommendationReason(StrEnum):
    BELOW_COMMERCIAL_FLOOR = "BELOW_COMMERCIAL_FLOOR"
    BELOW_TARGET_MARGIN = "BELOW_TARGET_MARGIN"
    ABOVE_TARGET_MARGIN = "ABOVE_TARGET_MARGIN"
    REPLACEMENT_COST_INCREASED = "REPLACEMENT_COST_INCREASED"
    REPLACEMENT_COST_DECREASED = "REPLACEMENT_COST_DECREASED"
    CHANGE_BELOW_MINIMUM = "CHANGE_BELOW_MINIMUM"
    CHANGE_EXCEEDS_GUARDRAIL = "CHANGE_EXCEEDS_GUARDRAIL"
    MISSING_COST = "MISSING_COST"
    MISSING_CURRENT_PRICE = "MISSING_CURRENT_PRICE"
    STALE_COST = "STALE_COST"
    STALE_PRICE = "STALE_PRICE"
    LOW_COST_CONFIDENCE = "LOW_COST_CONFIDENCE"
    MARKET_SIGNAL_WARNING = "MARKET_SIGNAL_WARNING"
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    AT_TARGET = "AT_TARGET"
