from enum import StrEnum


class RankingMode(StrEnum):
    RAW = "RAW"
    DELIVERED = "DELIVERED"
    FINANCIAL_EQUIVALENT = "FINANCIAL_EQUIVALENT"


class RankingScope(StrEnum):
    BEST_PER_DISTRIBUTOR = "BEST_PER_DISTRIBUTOR"
    ALL_OFFERS = "ALL_OFFERS"


class EligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    ELIGIBLE_WITH_WARNINGS = "ELIGIBLE_WITH_WARNINGS"
    INELIGIBLE = "INELIGIBLE"


class ReasonSeverity(StrEnum):
    BLOCKING = "BLOCKING"
    WARNING = "WARNING"
    INFORMATION = "INFORMATION"


class ComparisonRunStatus(StrEnum):
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


METHODOLOGY_VERSION = "QUOTE_COMPARISON_V1"
FINANCIAL_METHODOLOGY_VERSION = "EFFECTIVE_ANNUAL_V1"
DEFAULT_DAY_COUNT_BASIS = 365
