from enum import StrEnum


class ErpConnectorType(StrEnum):
    XPERT_SQLSERVER = "XPERT_SQLSERVER"


class ErpConnectorMode(StrEnum):
    DIRECT = "DIRECT"


class ErpConnectionStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    CONNECTED = "CONNECTED"
    DEGRADED = "DEGRADED"
    DISCONNECTED = "DISCONNECTED"
    MISCONFIGURED = "MISCONFIGURED"
    DISABLED = "DISABLED"
    UNSAFE = "UNSAFE"


class ErpDatasetCode(StrEnum):
    STATIONS = "STATIONS"
    PRODUCTS = "PRODUCTS"
    SUPPLIERS = "SUPPLIERS"
    PAYMENT_METHODS = "PAYMENT_METHODS"
    FUEL_SALES_ITEMS = "FUEL_SALES_ITEMS"
    FUEL_RETAIL_PRICES = "FUEL_RETAIL_PRICES"
    FUEL_SALE_PAYMENTS = "FUEL_SALE_PAYMENTS"


class ErpSecurityStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    SAFE = "SAFE"
    UNSAFE = "UNSAFE"


class ErpSyncMode(StrEnum):
    FULL = "FULL"
    INCREMENTAL_TIMESTAMP = "INCREMENTAL_TIMESTAMP"
    INCREMENTAL_ID = "INCREMENTAL_ID"
    FULL_SNAPSHOT_HASH = "FULL_SNAPSHOT_HASH"


class ErpCheckpointType(StrEnum):
    TIMESTAMP = "TIMESTAMP"
    MONOTONIC_ID = "MONOTONIC_ID"
    NONE = "NONE"


class ErpContractStatus(StrEnum):
    PENDING = "PENDING"
    VALID = "VALID"
    INVALID = "INVALID"
    MISCONFIGURED = "MISCONFIGURED"
    PENDING_VALIDATION = "PENDING_VALIDATION"


class ErpSyncRunStatus(StrEnum):
    QUEUED = "QUEUED"
    CONNECTING = "CONNECTING"
    EXTRACTING = "EXTRACTING"
    STAGING = "STAGING"
    VALIDATING = "VALIDATING"
    APPLYING = "APPLYING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLATION_REQUESTED = "CANCELLATION_REQUESTED"
    CANCELLED = "CANCELLED"
    SKIPPED_LOCKED = "SKIPPED_LOCKED"


class ErpSyncTrigger(StrEnum):
    MANUAL = "MANUAL"
    SCHEDULED = "SCHEDULED"
    RETRY = "RETRY"
    INITIAL_FULL = "INITIAL_FULL"


class ErpStagingStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATED = "VALIDATED"
    APPLIED = "APPLIED"
    SKIPPED_UNCHANGED = "SKIPPED_UNCHANGED"
    QUARANTINED = "QUARANTINED"
    ERROR = "ERROR"


class ErpSyncPhase(StrEnum):
    CONNECT = "CONNECT"
    EXTRACT = "EXTRACT"
    STAGE = "STAGE"
    VALIDATE = "VALIDATE"
    APPLY = "APPLY"
    CHECKPOINT = "CHECKPOINT"
